USE [SalesMine]
GO

/****** Object:  Table [dbo].[PageList]    Script Date: 12/02/2013 20:45:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PageList](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PageName] [varchar](100) NULL,
 CONSTRAINT [PK_PageList] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


